import type { ExtractedSection } from "./ai.js";
import { TutorError } from "./errors.js";

export interface Transcript {
  videoId: string;
  title: string;
  /** Captions YouTube generated by speech recognition rather than ones a person wrote. */
  auto: boolean;
  segments: Array<{ startMs: number; durationMs?: number | undefined; text: string }>;
}

/** Where video transcripts come from. One seam, so tests never reach YouTube. */
export interface TranscriptSource {
  fetch(videoId: string): Promise<Transcript>;
}

const MAX_SECTIONS = 60;
const WINDOW_MS = 2 * 60 * 1000;
const MAX_SECTION_CHARS = 2_000;
const MAX_TEXT_SECTION_CHARS = 1_500;
const MAX_TRANSCRIPT_CHARS = 200_000;
const VIDEO_ID = /^[A-Za-z0-9_-]{11}$/;

/** Accepts the forms people paste: watch, youtu.be, shorts, embed and live links. */
export function youtubeVideoId(link: string): string | null {
  let url: URL;
  try {
    url = new URL(link.trim());
  } catch {
    return null;
  }
  const host = url.hostname.replace(/^(www|m|music)\./, "");
  let id: string | null = null;
  if (host === "youtu.be") id = url.pathname.slice(1).split("/")[0] ?? null;
  else if (host === "youtube.com" || host === "youtube-nocookie.com") {
    id = url.pathname === "/watch" ? url.searchParams.get("v") : (url.pathname.match(/^\/(?:shorts|embed|live|v)\/([^/]+)/)?.[1] ?? null);
  }
  return id && VIDEO_ID.test(id) ? id : null;
}

const clock = (ms: number) => {
  const s = Math.floor(ms / 1000);
  const h = Math.floor(s / 3600);
  const mm = String(Math.floor((s % 3600) / 60)).padStart(h ? 2 : 1, "0");
  const ss = String(s % 60).padStart(2, "0");
  return h ? `${h}:${mm}:${ss}` : `${mm}:${ss}`;
};

/**
 * Two-minute stretches of the video, each cited by its time range so a card
 * can point back to the moment it came from. Machine captions mishear, but
 * flagging every stretch for review would make video unusable; they are marked
 * slightly less certain instead.
 */
export function transcriptSections(transcript: Transcript): ExtractedSection[] {
  const sections: ExtractedSection[] = [];
  let start = 0;
  let parts: string[] = [];
  let length = 0;
  let last = 0;
  const flush = () => {
    if (parts.length === 0) return;
    sections.push({
      heading: null,
      text: parts.join(" ").replace(/\s+/g, " ").trim(),
      confidence: transcript.auto ? 0.9 : 1,
      uncertainParts: [],
      sourceRef: `${clock(start)}–${clock(last)}`,
    });
    parts = [];
    length = 0;
  };
  for (const segment of transcript.segments) {
    if (parts.length > 0 && (segment.startMs - start >= WINDOW_MS || length + segment.text.length > MAX_SECTION_CHARS)) flush();
    if (parts.length === 0) start = segment.startMs;
    parts.push(segment.text);
    length += segment.text.length + 1;
    last = segment.startMs + (segment.durationMs ?? 0);
  }
  flush();
  return sections.filter((s) => s.text.length > 0).slice(0, MAX_SECTIONS);
}

/** Pasted notes, split at blank lines into parts of a readable size. */
export function textSections(text: string): ExtractedSection[] {
  const paragraphs = text
    .replace(/\r\n/g, "\n")
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean);
  const chunks: string[] = [];
  let current = "";
  for (const paragraph of paragraphs) {
    for (let i = 0; i < paragraph.length; i += MAX_TEXT_SECTION_CHARS) {
      const piece = paragraph.slice(i, i + MAX_TEXT_SECTION_CHARS);
      if (current && current.length + piece.length + 2 > MAX_TEXT_SECTION_CHARS) {
        chunks.push(current);
        current = "";
      }
      current = current ? `${current}\n\n${piece}` : piece;
    }
  }
  if (current) chunks.push(current);
  return chunks.slice(0, MAX_SECTIONS).map((chunk, i) => ({
    heading: null,
    text: chunk,
    confidence: 1,
    uncertainParts: [],
    sourceRef: `part ${i + 1}`,
  }));
}

interface CaptionTrack {
  baseUrl: string;
  languageCode?: string;
  kind?: string;
}

/**
 * Reads captions the way YouTube's own Android app does. There is no public
 * captions API for videos you do not own, so this can break when YouTube
 * changes; every failure says so plainly and suggests pasting the text instead.
 */
export class YoutubeTranscripts implements TranscriptSource {
  async fetch(videoId: string): Promise<Transcript> {
    const unavailable = () =>
      new TutorError("TRANSCRIPT_FAILED", "We could not get this video's captions right now. Paste its transcript or your notes instead.");

    let player: {
      playabilityStatus?: { status?: string };
      videoDetails?: { title?: string };
      captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] } };
    };
    try {
      const response = await fetch("https://www.youtube.com/youtubei/v1/player?prettyPrint=false", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "user-agent": "com.google.android.youtube/20.10.38 (Linux; U; Android 14)",
        },
        body: JSON.stringify({
          context: { client: { clientName: "ANDROID", clientVersion: "20.10.38", androidSdkVersion: 34, hl: "en" } },
          videoId,
        }),
        signal: AbortSignal.timeout(15_000),
      });
      if (!response.ok) throw unavailable();
      player = (await response.json()) as typeof player;
    } catch (error) {
      if (error instanceof TutorError) throw error;
      throw unavailable();
    }

    if (player.playabilityStatus?.status !== "OK") {
      throw new TutorError("VIDEO_UNAVAILABLE", "That video is private, removed or restricted, so TutorPAL cannot use it.");
    }
    const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    const english = (t: CaptionTrack) => t.languageCode?.startsWith("en");
    const track =
      tracks.find((t) => english(t) && t.kind !== "asr") ??
      tracks.find(english) ??
      tracks.find((t) => t.kind !== "asr") ??
      tracks[0];
    if (!track) {
      throw new TutorError("NO_TRANSCRIPT", "That video has no captions. Paste its transcript or your notes instead.");
    }

    let events: Array<{ tStartMs?: number; dDurationMs?: number; segs?: Array<{ utf8?: string }> }>;
    try {
      const url = new URL(track.baseUrl);
      url.searchParams.set("fmt", "json3");
      const response = await fetch(url, { signal: AbortSignal.timeout(15_000) });
      if (!response.ok) throw unavailable();
      events = ((await response.json()) as { events?: typeof events }).events ?? [];
    } catch (error) {
      if (error instanceof TutorError) throw error;
      throw unavailable();
    }

    let total = 0;
    const segments: Transcript["segments"] = [];
    for (const event of events) {
      const text = (event.segs ?? []).map((s) => s.utf8 ?? "").join("").replace(/\s+/g, " ").trim();
      if (!text) continue;
      total += text.length;
      if (total > MAX_TRANSCRIPT_CHARS) break;
      segments.push({ startMs: event.tStartMs ?? 0, durationMs: event.dDurationMs, text });
    }
    if (segments.length === 0) {
      throw new TutorError("NO_TRANSCRIPT", "That video has no captions. Paste its transcript or your notes instead.");
    }
    return { videoId, title: player.videoDetails?.title ?? "YouTube video", auto: track.kind === "asr", segments };
  }
}

let source: TranscriptSource | undefined;

export function transcriptSource(): TranscriptSource {
  if (!source) source = new YoutubeTranscripts();
  return source;
}

export function setTranscriptSource(next: TranscriptSource): void {
  source = next;
}
